name        : libpciaccess
version     : 0.13.3
release     : 5
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libpciaccess-0.13.3.tar.bz2 : 6cd76ccae4e06eee47d3ead84a118740e9406e2a9b7adc9b08e92c69ce89c2e3
license     :
    - GPL-3.0
summary     : Generic PCI access library for X
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
description : |
    Provides functionality for X to access the PCI bus and devices in a platform-independant way
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
