name       : libpciaccess
version    : 0.14
release    : 11
source     :
    - https://www.x.org/releases/individual/lib/libpciaccess-0.14.tar.gz : 8d86e64893917be3dfb1c5e837888d1275399c818783474002203d751312b03c
license    : MIT
component  : xorg.library
emul32     : yes
optimize   : speed
summary    : Generic PCI access library for X
description: |
    Provides functionality for X to access the PCI bus and devices in a platform-independant way
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
