name       : libpciaccess
version    : 0.13.4
release    : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libpciaccess-0.13.4.tar.gz : 74d92bda448e6fdb64fee4e0091255f48d625d07146a121653022ed3a0ca1f2f
license    :
    - MIT
summary    : Generic PCI access library for X
component  : xorg.library
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
description: |
    Provides functionality for X to access the PCI bus and devices in a platform-independant way
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
