name       : libpciaccess
version    : 0.13.5
release    : 9
source     :
    - https://www.x.org/releases/individual/lib/libpciaccess-0.13.5.tar.gz : fe26ec788732b4ef60b550f2d3fa51c605d27f646e18ecec878f061807a3526e
license    :
    - MIT
summary    : Generic PCI access library for X
component  : xorg.library
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
description: |
    Provides functionality for X to access the PCI bus and devices in a platform-independant way
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
